# https://docs.pytest.org/en/stable/reference/reference.html#ini-options-ref

[pytest]
pythonpath = src
addopts = --junit-xml=pytest/junit.xml --html=pytest/htmlunit/index.html --md-report --md-report-output=pytest/junit.md --cov --cov-report=xml --cov-report=html --cov-report=markdown:pytest/coverage.md --cov-report=term
