# https://docs.pytest.org/en/stable/reference/reference.html#ini-options-ref

[pytest]
pythonpath = src
addopts = --junit-xml=pytest/junit.xml --cov --cov-report=xml --cov-report=html --cov-report=term
